language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode

gemfile:
  - Gemfile.ci

notifications:
  email:
    - jacob.hammack@hammackj.com
  irc: "irc.freenode.org#risu"

before_install:
  - gem update --system
  - gem --version
